version: "3.8"
services:
    dev:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: dev
        tty: true
        stdin_open: true
        ports:
            - 8000:8000
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings.local
            - GAMESTONE_API_URL=http://localhost:8000/gamestone/api/
        env_file:
            - .env.secret
        volumes:
            - .:/code
            - poetry:/home/docker/.cache
        depends_on:
            - database

    database:
        image: postgres:14
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=database
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:5432

    ci: &ci
        build:
            context: .
            dockerfile: ./Dockerfile
            target: build
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings.local
            - GAMESTONE_API_URL=http://localhost:8000/gamestone/api/
            - GIANTBOMB_API_KEY=foo
            - SENDGRID_API_KEY=foo
        depends_on:
            - database
    
    django_tests:
        <<: *ci
        command: "poetry run python manage.py test"

    flake8:
        <<: *ci
        command: "poetry run flake8"
    
    black:
        <<: *ci
        command: "poetry run python -m black . --check"

    eslint:
        <<: *ci
        command: "npx eslint ."

    prettier:
        <<: *ci
        command: "npx prettier . --check"


volumes:
    poetry:
    db:
